-- Down de 20260907172000_x3_function_execute_hardening.sql.
-- À APPLIQUER EN supabase_admin. Regrants générés depuis l'état de production
-- du 2026-09-07 avant le up.
--
-- Note de fidélité : 17 fonctions avaient une ACL NULL (défaut implicite).
-- Le up la matérialise ; ce down redonne EXECUTE à PUBLIC, ce qui produit une
-- ACL explicite {owner=X/owner,=X/owner} — identique au défaut implicite en
-- termes de privilèges effectifs (c'est la seule divergence attendue de la
-- comparaison ACL, elle est documentée dans X3_RAPPORT.md).

begin;

grant execute on function private.is_prospect_value_suppressed(p_scope prospect_suppression_scope, p_value text) to public;
grant execute on function public.appointments_auto_follow() to anon;
grant execute on function public.appointments_auto_follow() to authenticated;
grant execute on function public.appointments_auto_follow() to public;
grant execute on function public.appointments_record_relationship() to anon;
grant execute on function public.appointments_record_relationship() to authenticated;
grant execute on function public.appointments_record_relationship() to public;
grant execute on function public.assign_barber_professional() to anon;
grant execute on function public.assign_barber_professional() to authenticated;
grant execute on function public.assign_barber_professional() to public;
grant execute on function public.check_appointment_consistency() to anon;
grant execute on function public.check_appointment_consistency() to authenticated;
grant execute on function public.check_appointment_consistency() to public;
grant execute on function public.check_appointment_time_blocks() to anon;
grant execute on function public.check_appointment_time_blocks() to authenticated;
grant execute on function public.check_appointment_time_blocks() to public;
grant execute on function public.check_barber_exception_barber_consistency() to anon;
grant execute on function public.check_barber_exception_barber_consistency() to authenticated;
grant execute on function public.check_barber_exception_barber_consistency() to public;
grant execute on function public.check_barber_service_consistency() to anon;
grant execute on function public.check_barber_service_consistency() to authenticated;
grant execute on function public.check_barber_service_consistency() to public;
grant execute on function public.check_barber_staff_profile_consistency() to anon;
grant execute on function public.check_barber_staff_profile_consistency() to authenticated;
grant execute on function public.check_barber_staff_profile_consistency() to public;
grant execute on function public.check_barber_working_hours_barber_consistency() to anon;
grant execute on function public.check_barber_working_hours_barber_consistency() to authenticated;
grant execute on function public.check_barber_working_hours_barber_consistency() to public;
grant execute on function public.check_chair_location_consistency() to anon;
grant execute on function public.check_chair_location_consistency() to authenticated;
grant execute on function public.check_chair_location_consistency() to public;
grant execute on function public.check_customer_membership_consistency() to anon;
grant execute on function public.check_customer_membership_consistency() to authenticated;
grant execute on function public.check_customer_membership_consistency() to public;
grant execute on function public.check_invitation_location_consistency() to anon;
grant execute on function public.check_invitation_location_consistency() to authenticated;
grant execute on function public.check_invitation_location_consistency() to public;
grant execute on function public.check_location_hours_location_consistency() to anon;
grant execute on function public.check_location_hours_location_consistency() to authenticated;
grant execute on function public.check_location_hours_location_consistency() to public;
grant execute on function public.check_post_has_media() to anon;
grant execute on function public.check_post_has_media() to authenticated;
grant execute on function public.check_post_has_media() to public;
grant execute on function public.check_post_media_limit() to anon;
grant execute on function public.check_post_media_limit() to authenticated;
grant execute on function public.check_post_media_limit() to public;
grant execute on function public.check_post_services_consistency() to anon;
grant execute on function public.check_post_services_consistency() to authenticated;
grant execute on function public.check_post_services_consistency() to public;
grant execute on function public.check_posts_consistency() to anon;
grant execute on function public.check_posts_consistency() to authenticated;
grant execute on function public.check_posts_consistency() to public;
grant execute on function public.check_queue_entry_consistency() to anon;
grant execute on function public.check_queue_entry_consistency() to authenticated;
grant execute on function public.check_queue_entry_consistency() to public;
grant execute on function public.check_reviews_consistency() to anon;
grant execute on function public.check_reviews_consistency() to authenticated;
grant execute on function public.check_reviews_consistency() to public;
grant execute on function public.check_service_category_consistency() to anon;
grant execute on function public.check_service_category_consistency() to authenticated;
grant execute on function public.check_service_category_consistency() to public;
grant execute on function public.check_service_location_consistency() to anon;
grant execute on function public.check_service_location_consistency() to authenticated;
grant execute on function public.check_service_location_consistency() to public;
grant execute on function public.check_staff_profile_location_consistency() to anon;
grant execute on function public.check_staff_profile_location_consistency() to authenticated;
grant execute on function public.check_staff_profile_location_consistency() to public;
grant execute on function public.check_time_block_consistency() to anon;
grant execute on function public.check_time_block_consistency() to authenticated;
grant execute on function public.check_time_block_consistency() to public;
grant execute on function public.check_waitlist_entry_consistency() to anon;
grant execute on function public.check_waitlist_entry_consistency() to authenticated;
grant execute on function public.check_waitlist_entry_consistency() to public;
grant execute on function public.customer_profiles_issue_passport() to anon;
grant execute on function public.customer_profiles_issue_passport() to authenticated;
grant execute on function public.customer_profiles_issue_passport() to public;
grant execute on function public.enforce_appointment_transition() to anon;
grant execute on function public.enforce_appointment_transition() to authenticated;
grant execute on function public.enforce_appointment_transition() to public;
grant execute on function public.enforce_professional_claim_transition() to anon;
grant execute on function public.enforce_professional_claim_transition() to authenticated;
grant execute on function public.enforce_professional_claim_transition() to public;
grant execute on function public.enforce_queue_transition() to anon;
grant execute on function public.enforce_queue_transition() to authenticated;
grant execute on function public.enforce_queue_transition() to public;
grant execute on function public.guard_customer_professional_relationship() to anon;
grant execute on function public.guard_customer_professional_relationship() to authenticated;
grant execute on function public.guard_customer_professional_relationship() to public;
grant execute on function public.guard_customers_identity() to anon;
grant execute on function public.guard_customers_identity() to authenticated;
grant execute on function public.guard_customers_identity() to public;
grant execute on function public.guard_marketplace_publication() to anon;
grant execute on function public.guard_marketplace_publication() to authenticated;
grant execute on function public.guard_marketplace_publication() to public;
grant execute on function public.guard_passport_identity() to anon;
grant execute on function public.guard_passport_identity() to authenticated;
grant execute on function public.guard_passport_identity() to public;
grant execute on function public.guard_professional_application_update() to anon;
grant execute on function public.guard_professional_application_update() to authenticated;
grant execute on function public.guard_professional_application_update() to public;
grant execute on function public.guard_professional_identity() to anon;
grant execute on function public.guard_professional_identity() to authenticated;
grant execute on function public.guard_professional_identity() to public;
grant execute on function public.guard_professional_publication() to anon;
grant execute on function public.guard_professional_publication() to authenticated;
grant execute on function public.guard_professional_publication() to public;
grant execute on function public.handle_new_membership() to anon;
grant execute on function public.handle_new_membership() to authenticated;
grant execute on function public.handle_new_membership() to public;
grant execute on function public.handle_new_organization() to anon;
grant execute on function public.handle_new_organization() to authenticated;
grant execute on function public.handle_new_organization() to public;
grant execute on function public.handle_new_user() to anon;
grant execute on function public.handle_new_user() to authenticated;
grant execute on function public.handle_new_user() to public;
grant execute on function public.link_customer_from_contact_info() to anon;
grant execute on function public.link_customer_from_contact_info() to authenticated;
grant execute on function public.link_customer_from_contact_info() to public;
grant execute on function public.maintain_post_like_count() to anon;
grant execute on function public.maintain_post_like_count() to authenticated;
grant execute on function public.maintain_post_like_count() to public;
grant execute on function public.maintain_review_reputation() to anon;
grant execute on function public.maintain_review_reputation() to authenticated;
grant execute on function public.maintain_review_reputation() to public;
grant execute on function public.normalize_invitation_email() to anon;
grant execute on function public.normalize_invitation_email() to authenticated;
grant execute on function public.normalize_invitation_email() to public;
grant execute on function public.normalize_phone_number(p_raw text, p_country text) to public;
grant execute on function public.notify_new_appointment() to anon;
grant execute on function public.notify_new_appointment() to authenticated;
grant execute on function public.notify_new_appointment() to public;
grant execute on function public.notify_new_invitation() to anon;
grant execute on function public.notify_new_invitation() to authenticated;
grant execute on function public.notify_new_invitation() to public;
grant execute on function public.notify_organization_follow() to anon;
grant execute on function public.notify_organization_follow() to authenticated;
grant execute on function public.notify_organization_follow() to public;
grant execute on function public.notify_post_like() to anon;
grant execute on function public.notify_post_like() to authenticated;
grant execute on function public.notify_post_like() to public;
grant execute on function public.notify_professional_follow() to anon;
grant execute on function public.notify_professional_follow() to authenticated;
grant execute on function public.notify_professional_follow() to public;
grant execute on function public.notify_review_received() to anon;
grant execute on function public.notify_review_received() to authenticated;
grant execute on function public.notify_review_received() to public;
grant execute on function public.notify_review_reply() to anon;
grant execute on function public.notify_review_reply() to authenticated;
grant execute on function public.notify_review_reply() to public;
grant execute on function public.posts_guard_immutable_author() to anon;
grant execute on function public.posts_guard_immutable_author() to authenticated;
grant execute on function public.posts_guard_immutable_author() to public;
grant execute on function public.queue_entries_auto_follow() to anon;
grant execute on function public.queue_entries_auto_follow() to authenticated;
grant execute on function public.queue_entries_auto_follow() to public;
grant execute on function public.queue_entries_record_relationship() to anon;
grant execute on function public.queue_entries_record_relationship() to authenticated;
grant execute on function public.queue_entries_record_relationship() to public;
grant execute on function public.restrict_appointment_self_update() to anon;
grant execute on function public.restrict_appointment_self_update() to authenticated;
grant execute on function public.restrict_appointment_self_update() to public;
grant execute on function public.restrict_queue_entry_self_update() to anon;
grant execute on function public.restrict_queue_entry_self_update() to authenticated;
grant execute on function public.restrict_queue_entry_self_update() to public;
grant execute on function public.reviews_guard_immutable() to anon;
grant execute on function public.reviews_guard_immutable() to authenticated;
grant execute on function public.reviews_guard_immutable() to public;
grant execute on function public.set_appointment_blocked_range() to anon;
grant execute on function public.set_appointment_blocked_range() to authenticated;
grant execute on function public.set_appointment_blocked_range() to public;
grant execute on function public.set_appointment_request_expiry() to anon;
grant execute on function public.set_appointment_request_expiry() to authenticated;
grant execute on function public.set_appointment_request_expiry() to public;
grant execute on function public.set_interest_request_expiry() to anon;
grant execute on function public.set_interest_request_expiry() to authenticated;
grant execute on function public.set_interest_request_expiry() to public;
grant execute on function public.set_updated_at() to anon;
grant execute on function public.set_updated_at() to authenticated;
grant execute on function public.set_updated_at() to public;
grant execute on function public.stamp_passport_identity() to anon;
grant execute on function public.stamp_passport_identity() to authenticated;
grant execute on function public.stamp_passport_identity() to public;
grant execute on function public.suggested_currency_for_country(p_country_code text) to public;
grant execute on function public.suggested_timezone_for_country(p_country_code text) to public;

-- Les 17 fonctions qui étaient à ACL NULL (EXECUTE PUBLIC implicite) :
grant execute on function private.apply_reputation_delta(p_kind text, p_id uuid, p_sum_delta integer, p_count_delta integer) to public;
grant execute on function private.assert_experiment_exposure_limits() to public;
grant execute on function private.assert_whatsapp_sendable() to public;
grant execute on function private.booking_provider_observations_maintain_current() to public;
grant execute on function private.cancel_outreach_on_conversion() to public;
grant execute on function private.log_prospect_status_change() to public;
grant execute on function private.notify_social(p_user_id uuid, p_type notification_type, p_title text, p_body text, p_organization_id uuid, p_dedupe_key text) to public;
grant execute on function private.outreach_templates_stamp_approval() to public;
grant execute on function private.professional_posts_page(p_professional_id uuid, p_cursor timestamp with time zone, p_limit integer) to public;
grant execute on function private.prospect_duplicates_stamp_review() to public;
grant execute on function private.prospect_fit_scores_maintain_current() to public;
grant execute on function private.prospect_scores_sync_prospect() to public;
grant execute on function private.prospect_search_partitions_enforce_limits() to public;
grant execute on function private.prospect_suppressions_sync_prospect() to public;
grant execute on function private.prospects_sync_booking_provider() to public;
grant execute on function private.prospects_sync_fit_scores() to public;
grant execute on function private.whatsapp_accounts_reject_secrets() to public;

commit;
