#!/usr/bin/env bash
# FadeUp — writes infra/web/.env from values that already exist on this host.
#
# Exists so nobody has to copy an anon key around by hand, and so the value
# never appears in a shell history, a terminal scrollback, or an agent
# transcript: it is read from infra/supabase/.env and written straight to
# infra/web/.env, which is gitignored. Nothing is echoed.
#
# The anon key is public by construction — every visitor's browser receives
# it — but "public" is not a reason to be careless about where it lands.
#
# Usage:
#   scripts/prepare-web-env.sh [SUPABASE_URL]
#
# SUPABASE_URL defaults to https://fadeup.jasmean.com, which requires the
# host nginx to proxy /auth/v1/, /rest/v1/, /storage/v1/ and /realtime/v1/
# to Kong first (see infra/web/nginx-host-fadeup.conf.example). Pass the
# current origin explicitly to stage a build against the existing setup.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE_ENV="$REPO_ROOT/infra/supabase/.env"
TARGET_ENV="$REPO_ROOT/infra/web/.env"
SUPABASE_URL="${1:-https://fadeup.jasmean.com}"

if [[ ! -r "$SOURCE_ENV" ]]; then
  echo "cannot read $SOURCE_ENV — run this as a user in the fadeup group" >&2
  exit 1
fi

# Read without sourcing: infra/supabase/.env is a large file of unrelated
# secrets, and sourcing it would import every one of them into this shell.
anon_key="$(grep -E '^ANON_KEY=' "$SOURCE_ENV" | head -1 | cut -d= -f2- | tr -d '"'"'"'')"

if [[ -z "$anon_key" ]]; then
  echo "ANON_KEY not found in $SOURCE_ENV" >&2
  exit 1
fi

umask 077
cat > "$TARGET_ENV" <<EOF
# Generated by scripts/prepare-web-env.sh — do not commit (gitignored).
# Public build-time values only. No service_role key, no provider secret.
VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$anon_key
EOF

echo "wrote $TARGET_ENV"
echo "  VITE_SUPABASE_URL=$SUPABASE_URL"
echo "  VITE_SUPABASE_ANON_KEY=<${#anon_key} chars, not shown>"
