/**
 * Browser-only, non-authoritative identifiers (toast keys, list keys, etc).
 * Never use this for anything the server/DB must treat as authoritative —
 * prospect_jobs.id and similar are generated by Postgres
 * (`default gen_random_uuid()`) or a server-side RPC, not the browser.
 *
 * `crypto.randomUUID()` needs a secure context (HTTPS/localhost) and a
 * fairly recent browser, so it can be `undefined` — falling back to
 * `crypto.getRandomValues()` (much broader support) keeps this working
 * everywhere. `Math.random()` is never an acceptable fallback: it isn't
 * cryptographically random.
 */
export function createUuid(): string {
  if (typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID()
  }

  const bytes = crypto.getRandomValues(new Uint8Array(16))
  // `?? 0` is unreachable (fixed-size array) — it only satisfies
  // `noUncheckedIndexedAccess`, which the V2 tsconfig applies here too.
  bytes[6] = ((bytes[6] ?? 0) & 0x0f) | 0x40 // version 4
  bytes[8] = ((bytes[8] ?? 0) & 0x3f) | 0x80 // variant 10

  const hex = Array.from(bytes, (byte) => byte.toString(16).padStart(2, '0')).join('')
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`
}
